
//! Autogenerated weights for `pallet_contracts`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-02-27, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `i9`, CPU: `13th Gen Intel(R) Core(TM) i9-13900K`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/substrate
// benchmark
// pallet
// --chain=dev
// --steps=2
// --repeat=1
// --pallet=pallet_contracts
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./weights-dev-release/frame/contracts/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_contracts`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_contracts::WeightInfo for WeightInfo<T> {
	/// Storage: Contracts DeletionQueue (r:1 w:0)
	/// Proof: Contracts DeletionQueue (max_values: Some(1), max_size: Some(16642), added: 17137, mode: Measured)
	fn on_process_deletion_queue_batch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1594`
		// Minimum execution time: 4_374 nanoseconds.
		Weight::from_ref_time(4_374_000)
			.saturating_add(Weight::from_proof_size(1594))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `k` is `[0, 1024]`.
	fn on_initialize_per_trie_key(_k: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `347 + k * (69 ±0)`
		//  Estimated: `71625`
		// Minimum execution time: 11_766 nanoseconds.
		Weight::from_ref_time(649_929_000)
			.saturating_add(Weight::from_proof_size(71625))
			.saturating_add(T::DbWeight::get().reads(1025))
			.saturating_add(T::DbWeight::get().writes(1025))
	}
	/// Storage: Contracts DeletionQueue (r:1 w:1)
	/// Proof: Contracts DeletionQueue (max_values: Some(1), max_size: Some(16642), added: 17137, mode: Measured)
	/// The range of component `q` is `[0, 128]`.
	fn on_initialize_per_queue_item(_q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109 + q * (34 ±0)`
		//  Estimated: `5992`
		// Minimum execution time: 6_618 nanoseconds.
		Weight::from_ref_time(150_716_000)
			.saturating_add(Weight::from_proof_size(5992))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Contracts PristineCode (r:1 w:0)
	/// Proof: Contracts PristineCode (max_values: None, max_size: Some(125988), added: 128463, mode: Measured)
	/// Storage: Contracts CodeStorage (r:0 w:1)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// The range of component `c` is `[0, 61717]`.
	fn reinstrument(_c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `338`
		//  Estimated: `127445`
		// Minimum execution time: 33_313 nanoseconds.
		Weight::from_ref_time(2_023_529_000)
			.saturating_add(Weight::from_proof_size(127445))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `c` is `[0, 125952]`.
	fn call_with_code_per_byte(_c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `875`
		//  Estimated: `651805`
		// Minimum execution time: 261_777 nanoseconds.
		Weight::from_ref_time(2_380_918_000)
			.saturating_add(Weight::from_proof_size(651805))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Contracts OwnerInfoOf (r:1 w:1)
	/// Proof: Contracts OwnerInfoOf (max_values: None, max_size: Some(88), added: 2563, mode: Measured)
	/// Storage: Contracts Nonce (r:1 w:1)
	/// Proof: Contracts Nonce (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: System EventTopics (r:3 w:3)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// Storage: Contracts CodeStorage (r:0 w:1)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Contracts PristineCode (r:0 w:1)
	/// Proof: Contracts PristineCode (max_values: None, max_size: Some(125988), added: 128463, mode: Measured)
	/// The range of component `c` is `[0, 61717]`.
	/// The range of component `i` is `[0, 1048576]`.
	/// The range of component `s` is `[0, 1048576]`.
	fn instantiate_with_code(c: u32, i: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `25479`
		// Minimum execution time: 3_082_258 nanoseconds.
		Weight::from_ref_time(1_001_306_335)
			.saturating_add(Weight::from_proof_size(25479))
			// Standard Error: 4_467
			.saturating_add(Weight::from_ref_time(52_495).saturating_mul(c.into()))
			// Standard Error: 262
			.saturating_add(Weight::from_ref_time(911).saturating_mul(i.into()))
			// Standard Error: 262
			.saturating_add(Weight::from_ref_time(1_072).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Contracts Nonce (r:1 w:1)
	/// Proof: Contracts Nonce (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts OwnerInfoOf (r:1 w:1)
	/// Proof: Contracts OwnerInfoOf (max_values: None, max_size: Some(88), added: 2563, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `i` is `[0, 1048576]`.
	/// The range of component `s` is `[0, 1048576]`.
	fn instantiate(i: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `546`
		//  Estimated: `29067`
		// Minimum execution time: 1_317_921 nanoseconds.
		Weight::from_ref_time(212_710_000)
			.saturating_add(Weight::from_proof_size(29067))
			// Standard Error: 1
			.saturating_add(Weight::from_ref_time(1_181).saturating_mul(i.into()))
			// Standard Error: 1
			.saturating_add(Weight::from_ref_time(1_054).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	fn call() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `855`
		//  Estimated: `22095`
		// Minimum execution time: 152_811 nanoseconds.
		Weight::from_ref_time(152_811_000)
			.saturating_add(Weight::from_proof_size(22095))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Contracts OwnerInfoOf (r:1 w:1)
	/// Proof: Contracts OwnerInfoOf (max_values: None, max_size: Some(88), added: 2563, mode: Measured)
	/// Storage: System EventTopics (r:1 w:1)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// Storage: Contracts CodeStorage (r:0 w:1)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Contracts PristineCode (r:0 w:1)
	/// Proof: Contracts PristineCode (max_values: None, max_size: Some(125988), added: 128463, mode: Measured)
	/// The range of component `c` is `[0, 61717]`.
	fn upload_code(_c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `7366`
		// Minimum execution time: 518_192 nanoseconds.
		Weight::from_ref_time(4_070_503_000)
			.saturating_add(Weight::from_proof_size(7366))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Contracts OwnerInfoOf (r:1 w:1)
	/// Proof: Contracts OwnerInfoOf (max_values: None, max_size: Some(88), added: 2563, mode: Measured)
	/// Storage: System EventTopics (r:1 w:1)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// Storage: Contracts CodeStorage (r:0 w:1)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Contracts PristineCode (r:0 w:1)
	/// Proof: Contracts PristineCode (max_values: None, max_size: Some(125988), added: 128463, mode: Measured)
	fn remove_code() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `287`
		//  Estimated: `8078`
		// Minimum execution time: 26_955 nanoseconds.
		Weight::from_ref_time(26_955_000)
			.saturating_add(Weight::from_proof_size(8078))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts OwnerInfoOf (r:2 w:2)
	/// Proof: Contracts OwnerInfoOf (max_values: None, max_size: Some(88), added: 2563, mode: Measured)
	/// Storage: System EventTopics (r:3 w:3)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	fn set_code() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `666`
		//  Estimated: `19818`
		// Minimum execution time: 32_135 nanoseconds.
		Weight::from_ref_time(32_135_000)
			.saturating_add(Weight::from_proof_size(19818))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_caller(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `875 + r * (480 ±0)`
		//  Estimated: `70205`
		// Minimum execution time: 247_610 nanoseconds.
		Weight::from_ref_time(625_274_000)
			.saturating_add(Weight::from_proof_size(70205))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1601 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_is_contract(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `876 + r * (21771 ±0)`
		//  Estimated: `6159345`
		// Minimum execution time: 254_892 nanoseconds.
		Weight::from_ref_time(4_057_388_000)
			.saturating_add(Weight::from_proof_size(6159345))
			.saturating_add(T::DbWeight::get().reads(1606))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1601 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_code_hash(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `885 + r * (22093 ±0)`
		//  Estimated: `6191595`
		// Minimum execution time: 253_609 nanoseconds.
		Weight::from_ref_time(5_170_456_000)
			.saturating_add(Weight::from_proof_size(6191595))
			.saturating_add(T::DbWeight::get().reads(1606))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_own_code_hash(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `882 + r * (480 ±0)`
		//  Estimated: `70240`
		// Minimum execution time: 247_358 nanoseconds.
		Weight::from_ref_time(762_690_000)
			.saturating_add(Weight::from_proof_size(70240))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_caller_is_origin(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `872 + r * (240 ±0)`
		//  Estimated: `46190`
		// Minimum execution time: 248_788 nanoseconds.
		Weight::from_ref_time(383_843_000)
			.saturating_add(Weight::from_proof_size(46190))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_address(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `876 + r * (480 ±0)`
		//  Estimated: `70210`
		// Minimum execution time: 242_703 nanoseconds.
		Weight::from_ref_time(631_070_000)
			.saturating_add(Weight::from_proof_size(70210))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_gas_left(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `877 + r * (480 ±0)`
		//  Estimated: `70215`
		// Minimum execution time: 242_711 nanoseconds.
		Weight::from_ref_time(633_759_000)
			.saturating_add(Weight::from_proof_size(70215))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:2 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_balance(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `876 + r * (488 ±0)`
		//  Estimated: `73545`
		// Minimum execution time: 248_457 nanoseconds.
		Weight::from_ref_time(2_366_335_000)
			.saturating_add(Weight::from_proof_size(73545))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_value_transferred(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `923 + r * (478 ±0)`
		//  Estimated: `70260`
		// Minimum execution time: 243_008 nanoseconds.
		Weight::from_ref_time(632_620_000)
			.saturating_add(Weight::from_proof_size(70260))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_minimum_balance(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `884 + r * (480 ±0)`
		//  Estimated: `70250`
		// Minimum execution time: 246_826 nanoseconds.
		Weight::from_ref_time(622_923_000)
			.saturating_add(Weight::from_proof_size(70250))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_block_number(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `881 + r * (480 ±0)`
		//  Estimated: `70235`
		// Minimum execution time: 245_856 nanoseconds.
		Weight::from_ref_time(624_094_000)
			.saturating_add(Weight::from_proof_size(70235))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_now(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `872 + r * (480 ±0)`
		//  Estimated: `70190`
		// Minimum execution time: 251_167 nanoseconds.
		Weight::from_ref_time(627_088_000)
			.saturating_add(Weight::from_proof_size(70190))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: TransactionPayment NextFeeMultiplier (r:1 w:0)
	/// Proof: TransactionPayment NextFeeMultiplier (max_values: Some(1), max_size: Some(16), added: 511, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_weight_to_fee(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `883 + r * (803 ±0)`
		//  Estimated: `121017`
		// Minimum execution time: 248_617 nanoseconds.
		Weight::from_ref_time(1_915_679_000)
			.saturating_add(Weight::from_proof_size(121017))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_gas(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `839 + r * (321 ±0)`
		//  Estimated: `54210`
		// Minimum execution time: 135_129 nanoseconds.
		Weight::from_ref_time(242_158_000)
			.saturating_add(Weight::from_proof_size(54210))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_input(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `874 + r * (480 ±0)`
		//  Estimated: `70200`
		// Minimum execution time: 247_625 nanoseconds.
		Weight::from_ref_time(512_517_000)
			.saturating_add(Weight::from_proof_size(70200))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 1024]`.
	fn seal_input_per_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1356`
		//  Estimated: `24600`
		// Minimum execution time: 261_039 nanoseconds.
		Weight::from_ref_time(6_020_064_000)
			.saturating_add(Weight::from_proof_size(24600))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 1]`.
	fn seal_return(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `864 + r * (45 ±0)`
		//  Estimated: `22365`
		// Minimum execution time: 244_565 nanoseconds.
		Weight::from_ref_time(247_352_000)
			.saturating_add(Weight::from_proof_size(22365))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 1024]`.
	fn seal_return_per_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `909`
		//  Estimated: `22365`
		// Minimum execution time: 249_725 nanoseconds.
		Weight::from_ref_time(480_019_000)
			.saturating_add(Weight::from_proof_size(22365))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:4 w:4)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: Contracts DeletionQueue (r:1 w:1)
	/// Proof: Contracts DeletionQueue (max_values: Some(1), max_size: Some(16642), added: 17137, mode: Measured)
	/// Storage: Contracts OwnerInfoOf (r:1 w:1)
	/// Proof: Contracts OwnerInfoOf (max_values: None, max_size: Some(88), added: 2563, mode: Measured)
	/// Storage: System EventTopics (r:3 w:3)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 1]`.
	fn seal_terminate(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `906 + r * (452 ±0)`
		//  Estimated: `42176`
		// Minimum execution time: 243_863 nanoseconds.
		Weight::from_ref_time(318_499_000)
			.saturating_add(Weight::from_proof_size(42176))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	/// Proof: RandomnessCollectiveFlip RandomMaterial (max_values: Some(1), max_size: Some(2594), added: 3089, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_random(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `877 + r * (802 ±0)`
		//  Estimated: `120831`
		// Minimum execution time: 252_650 nanoseconds.
		Weight::from_ref_time(2_647_876_000)
			.saturating_add(Weight::from_proof_size(120831))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_deposit_event(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `872 + r * (800 ±0)`
		//  Estimated: `102190`
		// Minimum execution time: 240_934 nanoseconds.
		Weight::from_ref_time(4_615_815_000)
			.saturating_add(Weight::from_proof_size(102190))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:322 w:322)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `t` is `[0, 4]`.
	/// The range of component `n` is `[0, 16]`.
	fn seal_deposit_event_per_topic_and_kb(t: u32, n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1778 + t * (2600 ±0) + n * (10 ±0)`
		//  Estimated: `26710 + t * (211000 ±0) + n * (50 ±0)`
		// Minimum execution time: 1_119_040 nanoseconds.
		Weight::from_ref_time(494_666_500)
			.saturating_add(Weight::from_proof_size(26710))
			// Standard Error: 1_719_709
			.saturating_add(Weight::from_ref_time(158_893_125).saturating_mul(t.into()))
			// Standard Error: 429_927
			.saturating_add(Weight::from_ref_time(39_023_343).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().reads((80_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((80_u64).saturating_mul(t.into())))
			.saturating_add(Weight::from_proof_size(211000).saturating_mul(t.into()))
			.saturating_add(Weight::from_proof_size(50).saturating_mul(n.into()))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_debug_message(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `871 + r * (560 ±0)`
		//  Estimated: `78185`
		// Minimum execution time: 145_678 nanoseconds.
		Weight::from_ref_time(329_737_000)
			.saturating_add(Weight::from_proof_size(78185))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: MaxEncodedLen)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: MaxEncodedLen)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `i` is `[0, 1024]`.
	fn seal_debug_message_per_kb(_i: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `125822`
		//  Estimated: `270072`
		// Minimum execution time: 320_991 nanoseconds.
		Weight::from_ref_time(996_215_000)
			.saturating_add(Weight::from_proof_size(270072))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 10]`.
	fn seal_set_storage(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `911 + r * (23408 ±0)`
		//  Estimated: `235000`
		// Minimum execution time: 248_192 nanoseconds.
		Weight::from_ref_time(3_556_065_000)
			.saturating_add(Weight::from_proof_size(235000))
			.saturating_add(T::DbWeight::get().reads(806))
			.saturating_add(T::DbWeight::get().writes(803))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 8]`.
	fn seal_set_storage_per_new_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2070 + n * (13142 ±0)`
		//  Estimated: `107206`
		// Minimum execution time: 379_964 nanoseconds.
		Weight::from_ref_time(897_558_000)
			.saturating_add(Weight::from_proof_size(107206))
			.saturating_add(T::DbWeight::get().reads(87))
			.saturating_add(T::DbWeight::get().writes(85))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 8]`.
	fn seal_set_storage_per_old_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2070 + n * (177305 ±0)`
		//  Estimated: `1420517`
		// Minimum execution time: 373_489 nanoseconds.
		Weight::from_ref_time(742_032_000)
			.saturating_add(Weight::from_proof_size(1420517))
			.saturating_add(T::DbWeight::get().reads(86))
			.saturating_add(T::DbWeight::get().writes(83))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 10]`.
	fn seal_clear_storage(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `874 + r * (23092 ±0)`
		//  Estimated: `231800`
		// Minimum execution time: 248_738 nanoseconds.
		Weight::from_ref_time(3_489_918_000)
			.saturating_add(Weight::from_proof_size(231800))
			.saturating_add(T::DbWeight::get().reads(806))
			.saturating_add(T::DbWeight::get().writes(803))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 8]`.
	fn seal_clear_storage_per_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1615 + n * (177322 ±0)`
		//  Estimated: `1420197`
		// Minimum execution time: 347_927 nanoseconds.
		Weight::from_ref_time(737_937_000)
			.saturating_add(Weight::from_proof_size(1420197))
			.saturating_add(T::DbWeight::get().reads(86))
			.saturating_add(T::DbWeight::get().writes(83))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 10]`.
	fn seal_get_storage(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `883 + r * (23732 ±0)`
		//  Estimated: `238211`
		// Minimum execution time: 250_823 nanoseconds.
		Weight::from_ref_time(2_960_867_000)
			.saturating_add(Weight::from_proof_size(238211))
			.saturating_add(T::DbWeight::get().reads(806))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 8]`.
	fn seal_get_storage_per_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1944 + n * (177363 ±0)`
		//  Estimated: `1420848`
		// Minimum execution time: 330_026 nanoseconds.
		Weight::from_ref_time(1_045_670_000)
			.saturating_add(Weight::from_proof_size(1420848))
			.saturating_add(T::DbWeight::get().reads(86))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 10]`.
	fn seal_contains_storage(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `914 + r * (23088 ±0)`
		//  Estimated: `231803`
		// Minimum execution time: 254_874 nanoseconds.
		Weight::from_ref_time(2_883_426_000)
			.saturating_add(Weight::from_proof_size(231803))
			.saturating_add(T::DbWeight::get().reads(806))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 8]`.
	fn seal_contains_storage_per_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1618 + n * (177322 ±0)`
		//  Estimated: `1420200`
		// Minimum execution time: 329_138 nanoseconds.
		Weight::from_ref_time(674_962_000)
			.saturating_add(Weight::from_proof_size(1420200))
			.saturating_add(T::DbWeight::get().reads(86))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 10]`.
	fn seal_take_storage(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `884 + r * (23732 ±0)`
		//  Estimated: `238212`
		// Minimum execution time: 250_462 nanoseconds.
		Weight::from_ref_time(3_589_445_000)
			.saturating_add(Weight::from_proof_size(238212))
			.saturating_add(T::DbWeight::get().reads(806))
			.saturating_add(T::DbWeight::get().writes(803))
	}
	/// Storage: Skipped Metadata (r:0 w:0)
	/// Proof Skipped: Skipped Metadata (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 8]`.
	fn seal_take_storage_per_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1945 + n * (177363 ±0)`
		//  Estimated: `1420849`
		// Minimum execution time: 355_557 nanoseconds.
		Weight::from_ref_time(1_260_377_000)
			.saturating_add(Weight::from_proof_size(1420849))
			.saturating_add(T::DbWeight::get().reads(86))
			.saturating_add(T::DbWeight::get().writes(83))
	}
	/// Storage: System Account (r:1602 w:1601)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_transfer(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `934 + r * (3630 ±0)`
		//  Estimated: `4348040`
		// Minimum execution time: 253_477 nanoseconds.
		Weight::from_ref_time(28_652_406_000)
			.saturating_add(Weight::from_proof_size(4348040))
			.saturating_add(T::DbWeight::get().reads(1607))
			.saturating_add(T::DbWeight::get().writes(1604))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1601 w:1601)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:2 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:1602 w:1602)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_call(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `898 + r * (23097 ±0)`
		//  Estimated: `10254570`
		// Minimum execution time: 251_344 nanoseconds.
		Weight::from_ref_time(331_876_090_000)
			.saturating_add(Weight::from_proof_size(10254570))
			.saturating_add(T::DbWeight::get().reads(3207))
			.saturating_add(T::DbWeight::get().writes(3203))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1536 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:1537 w:1537)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_delegate_call(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `883 + r * (74458 ±0)`
		//  Estimated: `15066375`
		// Minimum execution time: 256_138 nanoseconds.
		Weight::from_ref_time(327_263_436_000)
			.saturating_add(Weight::from_proof_size(15066375))
			.saturating_add(T::DbWeight::get().reads(3076))
			.saturating_add(T::DbWeight::get().writes(1538))
	}
	/// Storage: System Account (r:82 w:81)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:81 w:81)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:2 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:82 w:82)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `t` is `[0, 1]`.
	/// The range of component `c` is `[0, 1024]`.
	fn seal_call_per_transfer_clone_kb(t: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `24269 + t * (16910 ±0)`
		//  Estimated: `537640 + t * (285025 ±0)`
		// Minimum execution time: 8_445_116 nanoseconds.
		Weight::from_ref_time(7_076_083_499)
			.saturating_add(Weight::from_proof_size(537640))
			// Standard Error: 715_356_902
			.saturating_add(Weight::from_ref_time(1_369_032_500).saturating_mul(t.into()))
			// Standard Error: 698_590
			.saturating_add(Weight::from_ref_time(6_609_849).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(167))
			.saturating_add(T::DbWeight::get().reads((81_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().writes(163))
			.saturating_add(T::DbWeight::get().writes((81_u64).saturating_mul(t.into())))
			.saturating_add(Weight::from_proof_size(285025).saturating_mul(t.into()))
	}
	/// Storage: System Account (r:3202 w:3202)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1601 w:1601)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1601 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: Contracts Nonce (r:1 w:1)
	/// Proof: Contracts Nonce (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: Contracts OwnerInfoOf (r:1600 w:1600)
	/// Proof: Contracts OwnerInfoOf (max_values: None, max_size: Some(88), added: 2563, mode: Measured)
	/// Storage: System EventTopics (r:1602 w:1602)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_instantiate(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `918 + r * (25593 ±0)`
		//  Estimated: `27372223`
		// Minimum execution time: 253_510 nanoseconds.
		Weight::from_ref_time(455_282_847_000)
			.saturating_add(Weight::from_proof_size(27372223))
			.saturating_add(T::DbWeight::get().reads(9608))
			.saturating_add(T::DbWeight::get().writes(8006))
	}
	/// Storage: System Account (r:162 w:162)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:81 w:81)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:2 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: Contracts Nonce (r:1 w:1)
	/// Proof: Contracts Nonce (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: Contracts OwnerInfoOf (r:1 w:1)
	/// Proof: Contracts OwnerInfoOf (max_values: None, max_size: Some(88), added: 2563, mode: Measured)
	/// Storage: System EventTopics (r:82 w:82)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `t` is `[0, 1]`.
	/// The range of component `i` is `[0, 960]`.
	/// The range of component `s` is `[0, 960]`.
	fn seal_instantiate_per_transfer_input_salt_kb(t: u32, i: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5564 + t * (33 ±0)`
		//  Estimated: `856193 + t * (2706 ±0)`
		// Minimum execution time: 85_924_390 nanoseconds.
		Weight::from_ref_time(11_425_718_333)
			.saturating_add(Weight::from_proof_size(856193))
			// Standard Error: 7_088_000_321
			.saturating_add(Weight::from_ref_time(8_480_395_333).saturating_mul(t.into()))
			// Standard Error: 7_383_333
			.saturating_add(Weight::from_ref_time(68_769_037).saturating_mul(i.into()))
			// Standard Error: 7_383_333
			.saturating_add(Weight::from_ref_time(75_207_409).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(329))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(t.into())))
			.saturating_add(T::DbWeight::get().writes(326))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(t.into())))
			.saturating_add(Weight::from_proof_size(2706).saturating_mul(t.into()))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 1]`.
	fn seal_hash_sha2_256(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `871 + r * (642 ±0)`
		//  Estimated: `25385`
		// Minimum execution time: 245_646 nanoseconds.
		Weight::from_ref_time(270_847_000)
			.saturating_add(Weight::from_proof_size(25385))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 1024]`.
	fn seal_hash_sha2_256_per_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1513`
		//  Estimated: `26585`
		// Minimum execution time: 267_686 nanoseconds.
		Weight::from_ref_time(43_096_335_000)
			.saturating_add(Weight::from_proof_size(26585))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 1]`.
	fn seal_hash_keccak_256(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `873 + r * (642 ±0)`
		//  Estimated: `25395`
		// Minimum execution time: 253_332 nanoseconds.
		Weight::from_ref_time(292_221_000)
			.saturating_add(Weight::from_proof_size(25395))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 1024]`.
	fn seal_hash_keccak_256_per_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1515`
		//  Estimated: `26780`
		// Minimum execution time: 297_901 nanoseconds.
		Weight::from_ref_time(131_428_447_000)
			.saturating_add(Weight::from_proof_size(26780))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 1]`.
	fn seal_hash_blake2_256(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `873 + r * (642 ±0)`
		//  Estimated: `25395`
		// Minimum execution time: 243_707 nanoseconds.
		Weight::from_ref_time(275_329_000)
			.saturating_add(Weight::from_proof_size(25395))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 1024]`.
	fn seal_hash_blake2_256_per_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1515`
		//  Estimated: `26595`
		// Minimum execution time: 270_915 nanoseconds.
		Weight::from_ref_time(61_852_118_000)
			.saturating_add(Weight::from_proof_size(26595))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 1]`.
	fn seal_hash_blake2_128(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `873 + r * (679 ±0)`
		//  Estimated: `25580`
		// Minimum execution time: 246_795 nanoseconds.
		Weight::from_ref_time(270_808_000)
			.saturating_add(Weight::from_proof_size(25580))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `n` is `[0, 1024]`.
	fn seal_hash_blake2_128_per_kb(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1552`
		//  Estimated: `26595`
		// Minimum execution time: 278_692 nanoseconds.
		Weight::from_ref_time(62_075_786_000)
			.saturating_add(Weight::from_proof_size(26595))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 1]`.
	fn seal_ecdsa_recover(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `917 + r * (6083 ±0)`
		//  Estimated: `52820`
		// Minimum execution time: 239_940 nanoseconds.
		Weight::from_ref_time(1_988_480_000)
			.saturating_add(Weight::from_proof_size(52820))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 1]`.
	fn seal_ecdsa_to_eth_address(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `886 + r * (3362 ±0)`
		//  Estimated: `39060`
		// Minimum execution time: 254_317 nanoseconds.
		Weight::from_ref_time(755_211_000)
			.saturating_add(Weight::from_proof_size(39060))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1536 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: Contracts OwnerInfoOf (r:1536 w:1536)
	/// Proof: Contracts OwnerInfoOf (max_values: None, max_size: Some(88), added: 2563, mode: Measured)
	/// Storage: System EventTopics (r:1538 w:1538)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_set_code_hash(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `878 + r * (81746 ±0)`
		//  Estimated: `21235977`
		// Minimum execution time: 237_391 nanoseconds.
		Weight::from_ref_time(27_150_897_000)
			.saturating_add(Weight::from_proof_size(21235977))
			.saturating_add(T::DbWeight::get().reads(4613))
			.saturating_add(T::DbWeight::get().writes(3075))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_reentrance_count(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `867 + r * (240 ±0)`
		//  Estimated: `46165`
		// Minimum execution time: 244_233 nanoseconds.
		Weight::from_ref_time(387_848_000)
			.saturating_add(Weight::from_proof_size(46165))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_account_reentrance_count(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `884 + r * (3208 ±0)`
		//  Estimated: `343065`
		// Minimum execution time: 245_266 nanoseconds.
		Weight::from_ref_time(557_530_000)
			.saturating_add(Weight::from_proof_size(343065))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: System Account (r:1 w:0)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: Measured)
	/// Storage: Contracts ContractInfoOf (r:1 w:1)
	/// Proof: Contracts ContractInfoOf (max_values: None, max_size: Some(290), added: 2765, mode: Measured)
	/// Storage: Contracts CodeStorage (r:1 w:0)
	/// Proof: Contracts CodeStorage (max_values: None, max_size: Some(126001), added: 128476, mode: Measured)
	/// Storage: Timestamp Now (r:1 w:0)
	/// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: Contracts Nonce (r:1 w:1)
	/// Proof: Contracts Nonce (max_values: Some(1), max_size: Some(8), added: 503, mode: Measured)
	/// Storage: System EventTopics (r:2 w:2)
	/// Proof Skipped: System EventTopics (max_values: None, max_size: None, mode: Measured)
	/// The range of component `r` is `[0, 20]`.
	fn seal_instantiation_nonce(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `870 + r * (240 ±0)`
		//  Estimated: `53337`
		// Minimum execution time: 251_709 nanoseconds.
		Weight::from_ref_time(358_081_000)
			.saturating_add(Weight::from_proof_size(53337))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64const(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_070 nanoseconds.
		Weight::from_ref_time(16_227_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64load(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_213 nanoseconds.
		Weight::from_ref_time(33_649_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64store(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_287 nanoseconds.
		Weight::from_ref_time(92_744_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_select(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_944 nanoseconds.
		Weight::from_ref_time(38_828_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_if(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_487 nanoseconds.
		Weight::from_ref_time(51_718_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_br(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_437 nanoseconds.
		Weight::from_ref_time(28_854_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_br_if(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_483 nanoseconds.
		Weight::from_ref_time(32_957_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_br_table(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_485 nanoseconds.
		Weight::from_ref_time(50_845_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `e` is `[1, 256]`.
	fn instr_br_table_per_entry(_e: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_026 nanoseconds.
		Weight::from_ref_time(4_812_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_call(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_366 nanoseconds.
		Weight::from_ref_time(120_971_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_call_indirect(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_667 nanoseconds.
		Weight::from_ref_time(138_247_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `p` is `[0, 128]`.
	fn instr_call_indirect_per_param(_p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_332 nanoseconds.
		Weight::from_ref_time(25_516_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `l` is `[0, 1024]`.
	fn instr_call_per_local(_l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_057 nanoseconds.
		Weight::from_ref_time(44_643_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_local_get(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_664 nanoseconds.
		Weight::from_ref_time(16_862_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_local_set(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_809 nanoseconds.
		Weight::from_ref_time(18_200_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_local_tee(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_548 nanoseconds.
		Weight::from_ref_time(24_941_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_global_get(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_403 nanoseconds.
		Weight::from_ref_time(27_773_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_global_set(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_102 nanoseconds.
		Weight::from_ref_time(28_549_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_memory_current(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_204 nanoseconds.
		Weight::from_ref_time(27_617_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 1]`.
	fn instr_memory_grow(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_619 nanoseconds.
		Weight::from_ref_time(376_187_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64clz(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_439 nanoseconds.
		Weight::from_ref_time(22_649_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64ctz(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_493 nanoseconds.
		Weight::from_ref_time(22_430_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64popcnt(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_404 nanoseconds.
		Weight::from_ref_time(23_269_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64eqz(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_530 nanoseconds.
		Weight::from_ref_time(22_206_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64extendsi32(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_198 nanoseconds.
		Weight::from_ref_time(22_107_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64extendui32(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_340 nanoseconds.
		Weight::from_ref_time(22_871_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i32wrapi64(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_449 nanoseconds.
		Weight::from_ref_time(22_958_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64eq(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_032 nanoseconds.
		Weight::from_ref_time(46_728_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64ne(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 40_782 nanoseconds.
		Weight::from_ref_time(239_400_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64lts(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_075 nanoseconds.
		Weight::from_ref_time(31_875_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64ltu(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_524 nanoseconds.
		Weight::from_ref_time(30_433_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64gts(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_619 nanoseconds.
		Weight::from_ref_time(30_067_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64gtu(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_559 nanoseconds.
		Weight::from_ref_time(30_644_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64les(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_423 nanoseconds.
		Weight::from_ref_time(29_871_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64leu(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_441 nanoseconds.
		Weight::from_ref_time(29_827_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64ges(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_439 nanoseconds.
		Weight::from_ref_time(29_868_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64geu(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_381 nanoseconds.
		Weight::from_ref_time(30_350_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64add(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_528 nanoseconds.
		Weight::from_ref_time(30_086_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64sub(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_362 nanoseconds.
		Weight::from_ref_time(30_266_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64mul(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_396 nanoseconds.
		Weight::from_ref_time(30_305_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64divs(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_546 nanoseconds.
		Weight::from_ref_time(29_706_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64divu(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_471 nanoseconds.
		Weight::from_ref_time(29_575_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64rems(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_377 nanoseconds.
		Weight::from_ref_time(29_715_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64remu(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_430 nanoseconds.
		Weight::from_ref_time(32_338_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64and(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_409 nanoseconds.
		Weight::from_ref_time(30_255_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64or(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_379 nanoseconds.
		Weight::from_ref_time(29_872_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64xor(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_439 nanoseconds.
		Weight::from_ref_time(30_239_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64shl(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_602 nanoseconds.
		Weight::from_ref_time(30_369_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64shrs(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_431 nanoseconds.
		Weight::from_ref_time(30_024_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64shru(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_533 nanoseconds.
		Weight::from_ref_time(29_919_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64rotl(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_409 nanoseconds.
		Weight::from_ref_time(30_177_000)
			.saturating_add(Weight::from_proof_size(0))
	}
	/// The range of component `r` is `[0, 50]`.
	fn instr_i64rotr(_r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_029 nanoseconds.
		Weight::from_ref_time(30_634_000)
			.saturating_add(Weight::from_proof_size(0))
	}
}
